name: build-and-test
on:
  push:
    branches:
      - '**'
  pull_request:
  schedule:
    - cron: 0 4 * * *

jobs:
  validate_and_test_with_zig_master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: master
      - run: zig fmt --check *.zig src/*.zig
      - run: zig build
      - run: zig build test
  validate_and_test_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: master
      - run: zig build
      - run: zig build test
